# ============================================================
# Title:  TikZ export of UMG diagrams (umg-style dialect)
# File:   tikz.R (package umg)
# Author: H.-T. Yu
# Date:   2026-06-12
# ============================================================

# Internal: vertex type -> TikZ style name from umg-style.tex
.umg_tikz_style <- function(node) {
  if (node$role == "par") return("vP")
  if (node$role == "const") return("vK")
  if (node$role == "det")
    return(if (node$support == "categorical") "vDetD" else "vDetC")
  # role == "rv"
  if (node$support == "categorical") {
    if (node$observed) "vDO" else "vDL"
  } else {
    if (node$observed) "vCO" else "vCL"
  }
}

.umg_tikz_edge_style <- function(kind) {
  switch(kind, dep = "eReg", cov = "eCov", det = "eDet", mix = "eMix")
}

#' Export a UMG as TikZ code
#'
#' Generates a `tikzpicture` in the dialect of the umg-style.tex
#' lexicon distributed with the package (see
#' `system.file("tikz", "umg-style.tex", package = "umg")`), so that
#' programmatic diagrams are stylistically identical to hand-written
#' ones. The output compiles inside any document whose preamble loads
#' TikZ and inputs umg-style.tex.
#'
#' @param model An object of class `umg`; layout is computed if absent.
#' @param file Optional path; when supplied the code is written there.
#' @param digits Coordinate rounding (default 2).
#' @return The TikZ code as a character vector, invisibly when `file`
#'   is supplied.
#' @export
umg_to_tikz <- function(model, file = NULL, digits = 2) {
  if (is.null(model$layout)) model <- umg_layout(model)
  lay <- model$layout$vertices
  rects <- model$layout$plates

  # fixed-notation formatting: format = "fg" without an explicit digits
  # argument caps output at ~4 significant digits and silently corrupts
  # coordinates >= 100, so the rounding precision is passed through.
  # A value that rounds to zero from below would print as "-0"; it is
  # normalised to zero first.
  fmt <- function(v) {
    v <- round(v, digits)
    v[v == 0] <- 0
    formatC(v, format = "f", digits = digits, drop0trailing = TRUE)
  }
  out <- c("% Generated by umg::umg_to_tikz()",
           "% Requires \\input{umg-style} in the preamble.",
           "\\begin{tikzpicture}")

  # vertices
  for (v in model$nodes) {
    i <- match(v$name, lay$name)
    out <- c(out, sprintf("  \\node[%s] (%s) at (%s,%s) {%s};",
                          .umg_tikz_style(v), v$name,
                          fmt(lay$x[i]), fmt(lay$y[i]), v$label))
  }

  # edges
  for (e in model$edges) {
    style <- .umg_tikz_edge_style(e$kind)
    lab <- (if (!is.null(e$fixed)) as.character(e$fixed)
            else e$label) %||% ""
    bend <- if (e$kind == "cov") " to[bend left=35]" else " --"
    if (nzchar(lab)) {
      out <- c(out, sprintf(
        "  \\draw[%s] (%s)%s node[elab]{%s} (%s);",
        style, e$from, bend, lab, e$to))
    } else {
      out <- c(out, sprintf("  \\draw[%s] (%s)%s (%s);",
                            style, e$from, bend, e$to))
    }
  }

  # plates (background layer)
  if (length(rects)) {
    out <- c(out, "  \\begin{scope}[on background layer]")
    for (r in rects) {
      out <- c(out, sprintf(
        "    \\draw[plate] (%s,%s) rectangle (%s,%s);",
        fmt(r$x0), fmt(r$y0), fmt(r$x1), fmt(r$y1)))
    }
    out <- c(out, "  \\end{scope}")
    for (r in rects) {
      out <- c(out, sprintf(
        "  \\node[platelab] at (%s,%s) {%s};",
        fmt(r$x1), fmt(r$y0), r$index))
    }
  }

  # badge
  if (identical(model$badge, "structural")) {
    xr <- max(lay$x); yr <- max(lay$y)
    out <- c(out, sprintf(
      "  \\node[causalbadge] at (%s,%s) {structural $\\models$ do};",
      fmt(xr + 1.2), fmt(yr + 0.8)))
  }

  out <- c(out, "\\end{tikzpicture}")

  if (!is.null(file)) {
    writeLines(out, con = file)
    return(invisible(out))
  }
  out
}
